name: Docker build

on:
  push:
    branches: [main]
  schedule:
    - cron:  '0 0 * * *'

jobs:
  Bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm
      - name: Set up buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Build
        run: cd arm64v8-debian-11 && docker buildx build --platform linux/arm64 . -t weilbyte/box:arm64v8-debian-11 
        
